### ISSUE TITLE
Neuer Titel

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#25]
Vorschläge/Ideen?

- AirBnBerlin
- Die geshare-te Stadt
- Berlin vs AirBnB: Was sagen die Daten? (berlinvsairbnb.de)
- Share oder mehr?
- Ich share also vermiet ich nicht

**Comment by vogelino** [comment]
Final title: AirBnb vs Berlin? Was sagen die Daten?
Final Url: http://airbnbvsberlin.de/
