### ISSUE TITLE
Deutschlandkarte

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#26]
vielleicht ein bisschen kleiner machen? Wirkt noch ein bisschen zu groß.

**Comment by alsino** [comment]
Außerdem wäre es vielleicht besser für die Größe der Kreise nicht die absoluten Werte zu nehmen, sondern die Inserate pro 100 000 EW, um die unterschiedlichen Größen der Städte zu berücksichtigen. Hab das in dem Google-Spreadsheet auf dem 2ten Tabellenblatt schonmal gemacht. Guck dir das mal an und gib Feedback. Merci!

**Comment by z3to** [comment]
Habe jetzt noch ein zweites Diagramm dazu gemacht. Die relativen Mengen auf der Deutschland-Karte wäre zu verwirrend gewsen.
