### ISSUE TITLE
Kleine Änderungen users-chart 

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#27]
Änderungen beziehen sich hierauf: <div id="users-chart"></div>

1. Zwei kleine Tooltip-Rechtschreibefehler:
- "Anbieter" statt "Anbietern"
-  Column 1: "...können durchschnittlich 1 Schlafplatz anbieten"

2. Diagramm etwas weniger breit machen

3. Daten auf Google Drive und Link "Daten ansehen"

**Comment by vogelino** [comment]
Beim Punkt 4: Meinst du, dass die weisse Zone der Chart (die so aussieht, als ob es Null-Werte gäbe) zu gross ist? Oder meinst der gesamte Chart schmaler machen? 

Das Ding ist: wir haben bist jetzt immer alle Charts ein wenig breiter als den Text gemacht und würde gerne diese Konsistenz beibehalten. Zweitens, falls es darum geht, die Werte die kaum sichtbar sind zu entfernen wäre ich dagegen, da es doch noch Nutzern gibt die viele Plätze anbieten (selbst wenn wenige sind). Das ist inhaltlich wichtig zu sehen denke ich.

Eventuell habe ich es einfach nicht ganz gut verstanden… :worried:

**Comment by vogelino** [comment]
Habe es schmaler gemacht. Habe versucht es höher zu machen, um die geringe Werte sichtbar zu machen aber selbst das macht sie nicht sichtbar. Ich lasse erstmal so.
