### ISSUE TITLE
Edit Text from "Inserate"

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#31]

**Comment by vogelino** [comment]
Was ist hiermit gemeint? Das das Wort "Inserate" nirgendwo im text stehen sollte?

**Comment by alsino** [comment]
Nein, das war nur für mich, damit ich mir die Stelle merken konnte, wo ich aufgehört hab > Issue closed ;)

**Comment by vogelino** [comment]
Alles klar! Danke

2015-03-05 16:33 GMT+01:00 alsino <notifications@github.com>:

> Nein, das war nur für mich, damit ich mir die Stelle merken konnte, wo ich
> aufgehört hab > Issue closed ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/z3to/AirBNB/issues/31#issuecomment-77384924>.
>



-- 
Lucas Vogel
-
contact@vogelino.ch
www.vogelino.ch
