### ISSUE TITLE
Pressekit

### ISSUE THREAD

**Issue by z3to** [z3to/AirBNB#34]
Texte
Grafiken

**Comment by alsino** [comment]
Text mach ich,
Karte Export - Lucas
Andere Grafiken - Jonas

**Comment by alsino** [comment]
PDF - irgendjemand

**Comment by vogelino** [comment]
Die Choroplethenkarte ist jetzt vectorisiert und im Slack verfügbar.

**Comment by vogelino** [comment]
PDF Steht auch im Slack (braucht Schriftwechsel von Jonas > Freight text Pro + Whitney SSm)
