### ISSUE TITLE
#user-chart

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#40]
Marginalie ist bei Balkendiagramm “Anzahl Schlafplätze” (#users-chart) weiter links als bei allen anderen.

**Comment by vogelino** [comment]
Nochmal etwas was du mir gebeten hast zu ändern. Du meintest es sei zu breit und wir sollten es schmaler machen. Was denkst du? Sollte ich es rückgängig machen?

**Comment by alsino** [comment]
Ich glaube hier geht es um die Erklärung rechts neben dem Chart: 
Preisverteilung
Die Grafik zeigt die Preisverteilung der Berliner Airbnb-Angebote. Für jeden Preis (x-Achse) wird die Anzahl der angebotenen Unterkünfte dargestellt (y-Achse).
 Daten ansehen  Diese Grafik teilen 

>> Die ist irgendwie weiter links als bei den anderen Charts oder?

**Comment by vogelino** [comment]
Ach ja verstehe. Das kann ich machen ja… Sry, falsch verstanden! :disappointed:
