### ISSUE TITLE
Safari-Kompatibilität

### ISSUE THREAD

**Issue by alsino** [z3to/AirBNB#41]
Auf Mac (10.10.2) Safari (8.0.3) kann ich eure Seite gar nicht aufrufen. ??

**Comment by vogelino** [comment]
Ich habe das problem bei mir nicht und benutzte den selben Betriebssystem sowie Safari Version…

**Comment by alsino** [comment]
Mhh, vielleicht eine dritte Meinung? Jonas? ich hab ja leider kein Mac mehr ;)

**Comment by vogelino** [comment]
Meine aktuelle Konfiguration (Wie in der Beschreibung)
![bildschirmfoto 2015-03-12 um 19 41 45](https://cloud.githubusercontent.com/assets/2759340/6625378/f50d1756-c8ef-11e4-9375-b320c458fbd6.png)
![bildschirmfoto 2015-03-12 um 19 42 07](https://cloud.githubusercontent.com/assets/2759340/6625379/f510f650-c8ef-11e4-852d-21e8b06aece4.png)
![bildschirmfoto 2015-03-12 um 19 42 22](https://cloud.githubusercontent.com/assets/2759340/6625380/f51d436a-c8ef-11e4-9aa7-d9a1ed340663.png)

**Comment by z3to** [comment]
Also bei mir läuft es auch ohne Probleme.
Habe hier mit Chrome, Firefox und Safari auf Mac getestet.
Unter Windows simuliert funktioniert Firefox. Chrome hat Probleme bei den Diagrammen von C3 und IE8 hat auch noch ein paar Probleme. Das das können wir wahrscheinlich vernachlässigen ;)
Wie sieht es denn unter richtigem Windows mit anderen Browsern aus? @alsino

**Comment by alsino** [comment]
Hier der Windows Report: Chrome läuft super, Firefox auch. 
IE 11 macht ein paar Probleme: a) Parallax Effekt ruckelt beim Scrollen, b) Slider der Netzwerkkarte funktioniert nicht richtig (lädt schon zu Beginn alle Netzwerke und funktioniert nicht richtig, d.h. auch bei bspw. 6 Netzwerken zeigt er alle an)

**Comment by vogelino** [comment]
Ich habe eine BrowserStack account bei der Arbeit. Ich kann es dann ein bisschen tiefer testen. Allerdings würde ich je "Bug" ein neues Issue bei Github erstellen. Das sollte hier nur um das Safari Kompatibilitätsproblem gehen. Oder? (ps: ich weiss übrigens nicht was wir damit anfangen sollten…)

**Comment by alsino** [comment]
Ich hab gestern Safari nochmal an der FH auf den Macs im Labor getetstet und das ging auch. Gut ist würde ich sagen.
