### ISSUE TITLE
Linie bei Diagrammen

### ISSUE THREAD

**Issue by z3to** [z3to/AirBNB#47]
Marian hatte noch angemerkt, dass die grauen Linien beim Hover über die Diagramme twas stört.

**Comment by vogelino** [comment]
Da muss ich widersprechen, da sie helfen beim wissen worüber das tooltip berichtet wenn man nicht genau über das pinke Rechteck hovert. Was denkt ihr? Also ich würde es so lassen.

**Comment by alsino** [comment]
Ich find die Linie auch ok und würde sie drin lassen. Aber letztendlich wohl Geschmacksache ;)

**Comment by vogelino** [comment]
Naja, nicht nur, auch Verständlichkeit-Sache! :smile:

**Comment by alsino** [comment]
Yohooo ;)
