### ISSUE TITLE
Straßen Balkendiagramm

### ISSUE THREAD

**Issue by z3to** [z3to/AirBNB#7]

**Comment by vogelino** [comment]
Has a weird zooming interaction while dragging the y axis: to be removed/disabled

**Comment by vogelino** [comment]
It still needs the weird zoom to be disabled…

**Comment by vogelino** [comment]
Bar chart is done. The weird zoom exists as bug ticket: https://github.com/z3to/AirBNB/issues/12
That's why I'll close this ticket. :)
