### ISSUE TITLE
Beispiel Anzeigentexte

### ISSUE THREAD

**Issue by z3to** [z3to/AirBNB#8]
Größer machen. Vielleicht noch bessere raussuchen.

**Comment by z3to** [comment]
XBRG-LAUSI-GÖRLI chic apartment!
YEs we are in Kastanien allée !
Xberg 4families Stylish Oranienstr
X-Berg -pure living like a Berliner
WOW!!! Fantastic room in Neukölln!!
Wonderful stay to feel well
Wohnung für Kaffeeliebhaber
Wo Berlin am spannendsten ist
Wir lieben unsere Wohnung!
where real hipsters wish to live..
The greatest cultural extravaganza!
the crazy 20´s!
sweet duplex//best hood//long term
Sweet Dreams (romantic getaway!)

**Comment by vogelino** [comment]
Changed the titles for the following:
- X-Berg -pure living like a Berliner
- WOW!!! Fantastic room in Neukölln!!
- where real hipsters wish to live..
- 160m2 deluxe Dachgeschoss
- Luxury URBAN apt on KaDeWe/Ku'Damm
- central friedrichshain sexy cheap :)
- CHECKPOINT CHARLY KREUZBERG WIFI
- M❍ĐΞrn & ℃υsh✞y ℜ❍❍M ¡∩  NΞU Köɭɭn
